import { db } from "../server/db.js";
import { autoTimeSettings, workLogs } from "../shared/schema.js";
import { eq, and } from "drizzle-orm";
import type { AutoTimeSettings } from "../shared/schema.js";

// Scheduler simplificado para debug
export class SimpleAutoTimeScheduler {
  private interval: NodeJS.Timeout | null = null;

  constructor() {
    console.log('🚀 Initializing SIMPLE AutoTimeScheduler...');
    this.startSimpleScheduler();
  }

  startSimpleScheduler() {
    console.log('⏰ Starting SIMPLE scheduler (every 30 seconds)...');
    
    // Ejecutar cada 30 segundos para pruebas más rápidas
    this.interval = setInterval(async () => {
      await this.simpleCheck();
    }, 30000); // 30 segundos para pruebas
    
    // También ejecutar inmediatamente
    setTimeout(() => {
      console.log('🧪 Running immediate SIMPLE check...');
      this.simpleCheck();
    }, 3000); // 3 segundos para prueba inmediata
  }

  async simpleCheck() {
    try {
      console.log('🔄 SIMPLE check at:', new Date().toISOString());
      
      // Obtener hora actual en España
      const now = new Date();
      const spainTime = new Date(now.toLocaleString("en-US", { timeZone: "Europe/Madrid" }));
      const currentTime = spainTime.toTimeString().slice(0, 5);
      const currentDate = spainTime.toISOString().split('T')[0];
      
      console.log(`📍 Spain time: ${currentTime}, Date: ${currentDate}`);
      
      // Obtener TODAS las configuraciones (no filtrar por enabled para debug)
      const allSettings = await db.select().from(autoTimeSettings);
      console.log(`👥 Found ${allSettings.length} total auto time settings`);
      
      // Filtrar configuraciones habilitadas
      const enabledSettings = allSettings.filter(s => s.enabled);
      console.log(`✅ Found ${enabledSettings.length} ENABLED settings`);
      
      if (enabledSettings.length === 0) {
        console.log('⚠️ No ENABLED auto time settings found');
        return;
      }
      
      // Para cada configuración habilitada, intentar crear registro
      for (const settings of enabledSettings) {
        console.log(`👤 Processing user ${settings.userId}:`);
        console.log(`   - enabled: ${settings.enabled}`);
        console.log(`   - autoRegisterTime: ${settings.autoRegisterTime}`);
        console.log(`   - currentTime: ${currentTime}`);
        
        // SIMPLIFICADO: Siempre intentar crear registro (ignorar verificación de tiempo)
        console.log(`🔧 Forcing creation for user ${settings.userId}...`);
        
        try {
          // Verificar si ya existe registro
          const existingLog = await db.select()
            .from(workLogs)
            .where(and(
              eq(workLogs.userId, settings.userId),
              eq(workLogs.date, currentDate)
            ))
            .limit(1);

          console.log(`📋 Existing logs for today: ${existingLog.length}`);

          if (existingLog.length === 0) {
            // Crear nuevo registro
            await this.createSimpleWorkLog(settings, currentDate);
            console.log(`✅ Created SIMPLE work log for user ${settings.userId}`);
          } else {
            console.log(`ℹ️ User ${settings.userId} already has work log for today`);
          }
        } catch (error) {
          console.error(`❌ Error processing user ${settings.userId}:`, error);
        }
      }
    } catch (error) {
      console.error('❌ SIMPLE check error:', error);
    }
  }

  async createSimpleWorkLog(settings: AutoTimeSettings, date: string) {
    console.log(`🔧 Creating SIMPLE work log for user ${settings.userId} on ${date}`);
    
    try {
      // Calcular horas
      const [startHour, startMin] = settings.startTime.split(':').map(Number);
      const [endHour, endMin] = settings.endTime.split(':').map(Number);
      const totalMinutes = (endHour * 60 + endMin) - (startHour * 60 + startMin);
      
      console.log(`⏱️ Time: ${settings.startTime} to ${settings.endTime} = ${totalMinutes} minutes`);

      // Datos del registro
      const workLogData = {
        userId: settings.userId,
        date: date,
        startTime: settings.startTime,
        endTime: settings.endTime,
        totalHours: totalMinutes,
        type: 'work' as const,
        isAutoGenerated: true
      };

      console.log(`📝 Inserting:`, workLogData);

      // Insertar SIN .returning() para evitar problemas
      await db.insert(workLogs).values(workLogData);
      console.log(`✅ Inserted work log for user ${settings.userId}`);
      
      // Verificar inmediatamente
      const verification = await db.select()
        .from(workLogs)
        .where(and(
          eq(workLogs.userId, settings.userId),
          eq(workLogs.date, date),
          eq(workLogs.isAutoGenerated, true)
        ))
        .limit(1);
      
      if (verification.length > 0) {
        console.log(`🎉 VERIFIED! Work log exists with ID: ${verification[0].id}`);
        console.log(`📊 Record: user_id=${verification[0].userId}, date=${verification[0].date}, is_auto_generated=${verification[0].isAutoGenerated}`);
        return verification[0];
      } else {
        console.error(`❌ VERIFICATION FAILED! No record found after insertion`);
        return null;
      }
    } catch (error) {
      console.error(`❌ Error creating SIMPLE work log:`, error);
      throw error;
    }
  }

  stop() {
    if (this.interval) {
      clearInterval(this.interval);
      this.interval = null;
      console.log('🛑 Simple scheduler stopped');
    }
  }
}

// Variable global para el scheduler
let simpleScheduler: SimpleAutoTimeScheduler | null = null;

export function startSimpleAutoTimeScheduler() {
  if (!simpleScheduler) {
    simpleScheduler = new SimpleAutoTimeScheduler();
    console.log('✅ Simple AutoTimeScheduler started');
  } else {
    console.log('ℹ️ Simple AutoTimeScheduler already running');
  }
  return simpleScheduler;
}

export function getSimpleScheduler() {
  return simpleScheduler;
}

export function stopSimpleAutoTimeScheduler() {
  if (simpleScheduler) {
    simpleScheduler.stop();
    simpleScheduler = null;
    console.log('🛑 Simple AutoTimeScheduler stopped');
  }
}
